# Generated by Django 4.2.6 on 2023-10-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhtp_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='reason',
            field=models.TextField(default=''),
        ),
    ]
