# Generated by Django 4.2.6 on 2023-10-20 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhtp_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('provider', 'PROVIDER'), ('patient', 'PATIENT')], default='patient', max_length=11),
        ),
    ]
